name: "Test"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  call_job_1:
    uses: ./.github/workflows/reusable_action.yaml
    with:
      tag: "release/1.0.0"
      from: "master"

  call_job_2:
    uses: ./.github/workflows/reusable_action.yaml
    with:
      tag: "1.0.0"
      from: "master"
