name: "Test vars"

on:
  push:

jobs:
  pre-pull-request:
    uses: jlrosende/actions-test/.github/workflows/reusable_action.yaml@dev
    with:
      environment: pre
      tf_vars: |
        {
        "TF_VAR_AUTHORIZATION": "test-1",
        "TF_VAR_PROJECTID": "test-2"
        }
