name: "Test vars"

on:
  push:

jobs:
  pre-pull-request:
    uses: jlrosende/actions-test/.github/workflows/reusable_action.yaml@dev
    with:
      environment: pre
      tf_vars: |
        AUTHORIZATION
        PROJECTID
