name: "Test"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  call_job_1:
    uses: ./.github/workflows/reusable_action.yaml
  
  call_job_2:
    if: github.ref_name != 'master'
    uses: ./.github/workflows/reusable_action.yaml
    
  notify:
    if: always()
    runs-on: ubuntu-latest
    needs: 
      - call_job_1
      - call_job_2
    steps:
      - run: echo "${{ toJSON(needs.*.result) }}"
