name: "[Push dev] Build image and push"

on:
  push:
    branches:
      - dev

jobs:
  build_push:
    name: "Build and push DEV branch"
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: eu.gcr.io/test/collecting-data
          tags: |
            type=sha,prefix=dev-
            type=ref,event=branch
