name: "[Push dev] Build image and push"

on:
  push:
    branches:
      - dev

jobs:
  build_push:
    name: "Build and puhs dev branch"
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: dev

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: eu.gcr.io/test/collecting-data
          tags: |
            type=sha,prefix=dev-
            type=ref,event=branch
            type=semver,pattern={{raw}},value=dev-${{ steps.tag.outputs.new_tag }}
