name: "Workflow Dispatch"
run-name: "Workflow Dispatch"

on:
  workflow_dispatch:
    inputs:
      a:
        type: boolean
        required: true
        description: "Check if jobs"

jobs:
  test:
    if: !(inputs.a)
    uses: ./.github/workflows/reusable_action.yaml
    strategy:
      fail-fast: false
      matrix:
        a: [1, 2]
