name: "Workflow Dispatch"
run-name: "Workflow Dispatch ${{ inputs.var_1 }}"

on:
  workflow_dispatch:
    inputs:
      var_1:
        description: Variable de prueba
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Github context
        run: |
          echo "${{ toJSON(github) }}"

      - name: Setup SISU
        uses: ./.github/actions/setup-sisu
        with:
          token: ${{ secrets.GH_PAT }}
          version: v2.0.0
