name: "Workflow Dispatch"
run-name: "Workflow Dispatch"

on:
  workflow_dispatch:
    inputs:
      a:
        type: boolean
        required: true
        description: "Check if jobs"

jobs:
  test:
    # if: ${{ ! inputs.a }}
    # uses: ./.github/workflows/reusable_action.yaml
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     a: [1, 2]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test json value
        run: |
          echo "${{ fromJson('{"foo":"bar"}').baz.bazz || 'INFO' }}"

      - name: Setup Binary
        uses: ./actions/setup-binary
        with:
          token: ${{ secrets.GH_ORG_TOKEN }}
          version: v0.5.0
  
