name: "Workflow Dispatch"
run-name: "Workflow Dispatch"

on:
  # schedule: 
  #   - cron: "* * * * *"

  workflow_dispatch:
    inputs:
      foo:
        default: bar
        type: string
        required: true
      bar:
        default: baz
        type: string
        required: false

jobs:
  # remote:
  #   uses: ./.github/workflows/workflow_call.yaml
  #   with:
  #     foo: ${{ inputs.foo || 'bar' }}
  #     bar: ${{ inputs.bar || 'bazzzzz' }}

  e2e:
    runs-on: ubuntu-latest
    steps:
      # - run: exit 1 # -> error
      - run: |
          sleep 10
          exit 0 # -> ok

  manual-promotion:
    if: ${{ ! cancelled() && needs.e2e.result != 'success' }}
    needs: 
      - e2e
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - run: echo "Validate promotion"

  promote:
    if: ${{ ! cancelled() && (needs.manual-promotion.result == 'success' || needs.e2e.result == 'success') }}
    needs: 
      - manual-promotion
      - e2e
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ needs.manual-promotion.result }}"

  rollback:
    if: ${{ ! cancelled() && needs.manual-promotion.result == 'falied' }}
    needs: 
      - manual-promotion
    runs-on: ubuntu-latest
    steps:

      - run: |
          echo "${{ needs.manual-promotion.result }}"

  
