name: "Workflow Dispatch"
run-name: "Workflow Dispatch ${{ inputs.var_1 }}"

on:
  workflow_dispatch:
    inputs:
      var_1:
        description: Variable de prueba
        type: string
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Github context
        run: |
          echo "toJSON(github)"
          
      - name: Random number
        run: |
          echo "${RANDOM}"
