name: "Workflow Dispatch"
run-name: "Workflow Dispatch"

on:
  workflow_dispatch:

  schedule:
    - cron: "*/1 * * * *"

jobs:
  remote:
    uses: ./.github/workflows/workflow_call.yaml
    with:
      foo: bar
      
  test:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
  run-if-accetp:
    needs: 
      - test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ needs.test.result }}"

  run-if-cancel:
    if: ${{ ! cancelled() }}
    needs: 
      - test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ needs.test.result }}"

