name: "Exit code"

on:
  workflow_dispatch:

jobs:
  exit_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Github context
        continue-on-error: true
        id: color
        run: |
          echo "color=RED" >> $GITHUB_OUTPUT
          exit 42
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Print previous output
        run: |
          echo "${{ steps.color.outputs.color }}"
          echo "${{ steps.color.outputs.exit_code }}"
