name: "Terraform Format"

on:
  push:
    branches-ignore:
      - master
      - automated-terraform-fmt

jobs:
  format:
    name: "Terraform Format"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.6

      - name: Terraform fmt
        id: fmt
        run: terraform fmt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.8.2
        with:
          commit-message: terraform fmt
          title: Reformat terraform files
          body: Update terraform files to canonical format using `terraform fmt`
          branch: automated-terraform-fmt
          labels: automerge

  automerge:
    needs: format
    name: "Merge pr"
    runs-on: ubuntu-latest
    steps:
      - name: merge pr
        uses: pascalgn/automerge-action@v0.13.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: automerge
