name: "[Push int] Build image and push"

on:
  push:
    branches:
      - int

jobs:
  build_push:
    name: "Build and puhs int branch"
    runs-on: ubuntu-latest
    environment: int

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: test

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: eu.gcr.io//collecting-data
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix={{branch}}-
            type=raw,value={{branch}}
            type=semver,pattern={{raw}},value=${{ steps.tag.outputs.new_tag }}-dev
