name: "Open Issue"

on:
  issue_comment:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Github context
        run: |
          echo "${{ toJSON(github) }}"
          
      - uses: actions/checkout@v4

      - name: Checkout PR branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh pr checkout ${{ github.event.issue.number }}
      
      

