name: "PR/ISSUES Comments"

on:
  issue_comment:
    types:
      - created

jobs:
  build_push:
    name: "Build and push PRO branch"
    runs-on: ubuntu-latest
    environment: pro

    steps:
      - uses: actions/checkout@v2

      - name: Get Runner IP
        run: |
          curl https://api.ipify.org

      - name: Github Context
        run: |
          echo "${{ github.event.comment.body }}"
          echo "${{ toJson(github) }}"

      - name: View attributes
        uses: actions/github-script@v6
        with:
          script: |
            console.log(github.rest.issues)
            console.log(context.issue)

            github.rest.issues.addLabels({
              owner: context.issue.owner,
              repo: context.issue.repo,
              issue_number: context.issue.number,
              labels: [
                "test1",
                "test2"
              ]
            })
