name: "[Push pro] Build image and push"

on:
  push:
    branches:
      - main
      - master

jobs:
  build_push:
    name: "Build and push PRO branch"
    runs-on: ubuntu-latest
    environment: pro

    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          TAG_CONTEXT: branch

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: eu.gcr.io/test/collecting-data
          flavor: |
            latest=true
          tags: |
            type=semver,pattern=v{{major}},value=${{ steps.tag.outputs.new_tag }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ steps.tag.outputs.new_tag }}
            type=semver,pattern={{raw}},value=${{ steps.tag.outputs.new_tag }}
