name: "[Push pro] Build image and push"

on:
  push:
    branches:
      - main
      - master

jobs:
  build_push:
    name: "Build and puhs pro branch"
    runs-on: ubuntu-latest
    environment: pro

    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
