name: "[Push pro] Build image and push"

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  build_push:
    name: "Build and puhs pro branch"
    runs-on: ubuntu-latest
    environment: pro

    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: eu.gcr.io//collecting-data
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=tag

      - name: Print metadata
        run: |
          echo ${{ steps.meta.outputs.tags }}
          echo ${{ steps.meta.outputs.labels }}
          echo ${{ steps.meta.outputs.version }}
