name: "[Push pro] Build image and push"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_push:
    name: "Build and puhs pro branch"
    runs-on: ubuntu-latest
    environment: pro

    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: eu.gcr.io//collecting-data
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix={{branch}}-
            type=raw,value={{branch}}
