name: "PR"

on:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Github context
        run: |
          echo "${{ toJSON(github) }}"
