name: "PR"
run-name: "PR event.action: ${{ github.event.action }}"

on:
  pull_request:
    types: 
      - opened
      - reopened
      - edited
      - synchronize
      - closed
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Github context
        run: |
          echo "${{ toJSON(github) }}"

      - name: Github context
        run: |
          echo "github.head_ref = ${{ github.head_ref }}"
          echo "github.base_ref = ${{ github.base_ref }}"
          echo "github.sha = ${{ github.sha }}"
          echo "github.event.pull_request.head.sha = ${{ github.event.pull_request.head.sha }}"
          echo "github.event.pull_request.base.sha = ${{ github.event.pull_request.base.sha }}"
          