name: "RELEASE"

on:
  release: 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Github context
        run: |
          echo '${{ toJSON(github) }}'

      - name: Github release event
        run: |
          echo '${{ toJSON(github.event) }}'

      - name: Release body
        run: |
          echo '${{ toJSON(github.event.release.body) }}'
