name: "RELEASE"
run-name: "RELEASE ${{ github.ref_name }} [event: ${{ github.event.action }}]"
on:
  release: 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Github context
        env:
          context: ${{ toJSON(github) }}
        run: |
          echo "$context"

      - name: Github release event
        env:
          context: ${{ toJSON(github.event) }}
        run: |
          echo "$context"


      - name: Release body
        env:
          context: ${{ toJSON(github.event.release.body) }}
        run: |
          echo "$context"

