on:
  workflow_call:
 
jobs:
  printer:
    runs-on: ubuntu-latest
    steps:

      - name: GitHub Env Vars
        run: |
          echo $GITHUB_ENV

      - name: GitHub Job
        run: |
          echo $GITHUB_JOB
      
      - name: GitHub Context
        run: |
          echo "${{ toJSON(github) }}"
      
      - name: Job Context
        run: |
          echo "${{ toJSON(job) }}"

      - uses: actions/github-script@v6
        id: my-script
        with:
          result-encoding: string
          script: |
            const workflowJobs = github.actions.listJobsForWorkflowRun({
              owner: process.env.GITHUB_REPOSITORY_OWNER,
              repo: process.env.GITHUB_REPOSITORY,
              run_id: process.env.GITHUB_RUN_ID,
            });

            workflowJobs.data.jobs.find(
              (job: Octokit.ActionsListJobsForWorkflowRunResponseJobsItem) =>
                
                console.log(job.name)
                console.log(process.env.GITHUB_JOB)
            );
