name: "Fan-out"

on:
  workflow_dispatch: 

jobs:
  fan-out:
    runs-on: ubuntu-latest
    outputs:
      A-matrix: '[{"type":"a","num":1},{"type":"a","num":2}]'
      B-matrix: '[{"type":"b","num":1}]'
      C-matrix: '[]'
    steps:
      - uses: actions/checkout@v4
      
  A:
    name: Exec A
    needs: 
      - fan-out
    runs-on: ubuntu-lates
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.fan-out.outputs.A-matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Print A 
        run: |
          echo "${{ matrix.type }}-${{matrix.num}}"

  B:
    name: Exec B
    needs: 
      - fan-out
    runs-on: ubuntu-lates
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.fan-out.outputs.A-matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Print B
        run: |
          echo "${{ matrix.type }}-${{matrix.num}}"

  C:
    name: Exec A
    needs: 
      - fan-out
    runs-on: ubuntu-lates
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.fan-out.outputs.A-matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Print C
        run: |
          echo "${{ matrix.type }}-${{matrix.num}}"
