name: "Create Release"
run-name: "Create Release ${{ inputs.tag || github.head_ref }}"

on:
  workflow_call:
    inputs:
      tag:
        default: "New tag to create (format release/<tag>)"
        required: false
        type: string
      from:
        default: "Source of the release"
        required: false
        type: string

permissions: write-all

jobs:
  gen-tag:
    name: Create Release
    runs-on: ubuntu-latest

    outputs:
      new_tag: ${{ steps.get_tag.outputs.new_tag }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.from || github.sha }}
          fetch-depth: "0"

      - name: Create new tag
        id: get_tag
        env:
          TAG: ${{ inputs.from || github.head_ref }}
        run: |
          if [[ "${{ startsWith(env.TAG, 'release/') }}" == "false" ]]; then
            exit 1
          fi
          tag=$(echo "${{ inputs.from || github.head_ref }}" | sed 's|release/||' -)
          echo "new_tag=${tag}" >> $GITHUB_OUTPUT

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_TAG: ${{ inputs.tag || steps.get_tag.outputs.new_tag }}
        run: |
          gh release create $NEW_TAG --generate-notes --target ${{ inputs.from || 'main' }}
