name: "Fan-out"

on:
  workflow_dispatch: 

jobs:
  fan-out:
    runs-on: ubuntu-latest
    outputs:
      check: ${{ steps.check.outputs.num }}
    strategy:
      matrix:
        num: [0,1]
    steps:
      - id: check
        run: |
          if [[ "0" -eq "${{ matrix.num }}" ]]; then
            echo "num=${{ matrix.num }}" >> $GITHUB_OUTPUT
    
  result:
    runs-on: ubuntu-latest
    needs: 
      - fan-out
    steps:
      - run: echo "${{ needs.fan-out.outputs.check }}"
 
