on:
  workflow_call:
 
jobs:
  printer:
    runs-on: ubuntu-latest
    steps:

      - name: GitHub Env Vars
        run: |
          echo $GITHUB_ENV

      - name: GitHub Job
        run: |
          echo $GITHUB_JOB
      
      - name: GitHub Context
        run: |
          echo ${{ toJSON(github) }}
      
      - name: Job Context
        run: |
          echo ${{ toJSON(job) }}
