on:
  workflow_call:
 
jobs:
  printer:
    name: Otro nombre no basico
    runs-on: ubuntu-latest
    steps:

      - name: GitHub Env Vars
        run: |
          echo $GITHUB_ENV

      - name: GitHub Job
        run: |
          echo $GITHUB_JOB
      
      - name: GitHub Context
        run: |
          echo "${{ toJSON(github) }}"
      
      - name: Job Context
        run: |
          echo "${{ toJSON(job) }}"

      - name: Steps Context
        run: |
          echo "${{ toJSON(steps) }}"

      - uses: actions/github-script@v6
        id: my-script
        with:
          result-encoding: string
          script: |
            const [owner, repo] = (process.env.GITHUB_REPOSITORY || "").split("/");
            const workflowJobs = await github.rest.actions.listJobsForWorkflowRun({
              owner: owner,
              repo: repo,
              run_id: process.env.GITHUB_RUN_ID
            });

            console.log(process.env.GITHUB_JOB)
            console.log("------------------------------------------------------------")
            console.log(workflowJobs.data.jobs)
            console.log("------------------------------------------------------------")
