name: "Fan-out"

on:
  workflow_dispatch: 

jobs:
  fan-out:
    runs-on: ubuntu-latest
    outputs:
      check: ${{ steps.check.outputs.num }}
    strategy:
      matrix:
        include:
          - num: 10
          - num: 10
          - num: 15
    steps:
      - id: check
        run: |
          sleep ${{ matrix.num }}
          if [[ "10" -eq "${{ matrix.num }}" ]]; then
            echo "num=${{ matrix.num }}" >> $GITHUB_OUTPUT
          fi
    
  result:
    runs-on: ubuntu-latest
    needs: 
      - fan-out
    steps:
      - run: echo "${{ needs.fan-out.outputs.check }}"
 
