on:
  workflow_call:
    inputs:
      runner_type:
        description: Action Runner type
        default: ubuntu-latest
        required: false
        type: string
      tf_vars:
        description: Terraform variables
        default: ""
        required: false
        type: string
      environment:
        description: Terraform environment
        required: true
        type: string

jobs:
  terraform:
    name: "Terraform pull request"
    runs-on: ${{ inputs.runner_type }}
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v2

      - name: Inputs
        run: echo "${{ toJson(inputs) }}"

      - name: GitHub Context
        run: echo "${{ toJson(github) }}"

      - name: Setup env
        uses: jwulf/add-env-vars-action@master
        with:
          map: ${{ tojson(inputs) }}

      - name: GitHub Env Vars
        run: echo "${GITHUB_ENV}""
